// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwJD0XfIFUezbzf93bmooSyIXaOA71NVo',
    appId: '1:600223632016:web:f384577e75e3ae95aba615',
    messagingSenderId: '600223632016',
    projectId: 'walking-in-the-woods',
    authDomain: 'walking-in-the-woods.firebaseapp.com',
    storageBucket: 'walking-in-the-woods.firebasestorage.app',
    measurementId: 'G-MQ7XHR7BMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkvK0RrVZRZbOx0fu1fatfpwKYjNUdEyk',
    appId: '1:600223632016:android:d06ba41b03a39f1faba615',
    messagingSenderId: '600223632016',
    projectId: 'walking-in-the-woods',
    storageBucket: 'walking-in-the-woods.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKozE7Mwvjsy-tdQyzzbd8iHc-Z6Vkn_w',
    appId: '1:600223632016:ios:a15495c19a56f485aba615',
    messagingSenderId: '600223632016',
    projectId: 'walking-in-the-woods',
    storageBucket: 'walking-in-the-woods.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKozE7Mwvjsy-tdQyzzbd8iHc-Z6Vkn_w',
    appId: '1:600223632016:ios:a15495c19a56f485aba615',
    messagingSenderId: '600223632016',
    projectId: 'walking-in-the-woods',
    storageBucket: 'walking-in-the-woods.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwJD0XfIFUezbzf93bmooSyIXaOA71NVo',
    appId: '1:600223632016:web:575df6e2f9a03a6aaba615',
    messagingSenderId: '600223632016',
    projectId: 'walking-in-the-woods',
    authDomain: 'walking-in-the-woods.firebaseapp.com',
    storageBucket: 'walking-in-the-woods.firebasestorage.app',
    measurementId: 'G-DG1GW3QGY3',
  );
}
